#!/usr/bin/env python3
"""Generate paper assets (results table + figures) from benchmark outputs.

Reads ``results/summary.csv`` and ``results/plots/*.png`` produced by
``python -m benchmarks.run_benchmark`` and writes:

- ``paper/tables/results_table.tex``  -- a booktabs table of final-eval scores
- ``paper/figures/*.png``             -- copies of the learning-curve figures

Run from the repository root after the benchmark has completed::

    python paper/make_paper_assets.py
"""

from __future__ import annotations

import csv
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "results"
PAPER = ROOT / "paper"

# Order agents and environments deterministically for presentation.
AGENT_ORDER = ["Random", "TabularQ", "DQN", "NWM"]


def _load_summary() -> list[dict]:
    path = RESULTS / "summary.csv"
    if not path.exists():
        raise SystemExit(f"{path} not found. Run 'python -m benchmarks.run_benchmark' first.")
    with path.open(newline="") as f:
        return list(csv.DictReader(f))


def _fmt(value: str, digits: int = 1) -> str:
    try:
        return f"{float(value):.{digits}f}"
    except (TypeError, ValueError):
        return "--"


def write_results_table(rows: list[dict]) -> None:
    envs = []
    for r in rows:
        if r["env"] not in envs:
            envs.append(r["env"])

    # Index by (env, agent).
    idx = {(r["env"], r["agent"]): r for r in rows}
    agents = [a for a in AGENT_ORDER if any(r["agent"] == a for r in rows)]

    lines = [
        "% Auto-generated by paper/make_paper_assets.py -- do not edit by hand.",
        r"\begin{tabular}{ll" + "c" * len(agents) + "}",
        r"\toprule",
        "Environment & Metric & " + " & ".join(agents) + r" \\",
        r"\midrule",
    ]
    for env in envs:
        # Final evaluation row (mean +/- std).
        cells = []
        best_mean = None
        best_agent = None
        for a in agents:
            r = idx.get((env, a))
            if r is None:
                cells.append("--")
                continue
            m = float(r["final_eval_mean"])
            if best_mean is None or m > best_mean:
                best_mean, best_agent = m, a
        for a in agents:
            r = idx.get((env, a))
            if r is None:
                cells.append("--")
                continue
            txt = f"{_fmt(r['final_eval_mean'])} $\\pm$ {_fmt(r['final_eval_std'])}"
            if a == best_agent:
                txt = r"\textbf{" + txt + "}"
            cells.append(txt)
        lines.append(f"{env} & Final eval & " + " & ".join(cells) + r" \\")

        # AUC row (sample efficiency).
        auc_cells = []
        for a in agents:
            r = idx.get((env, a))
            auc_cells.append(_fmt(r["auc"]) if r else "--")
        lines.append(" & AUC & " + " & ".join(auc_cells) + r" \\")
        lines.append(r"\midrule")

    if lines[-1] == r"\midrule":
        lines[-1] = r"\bottomrule"
    else:
        lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")

    out = PAPER / "tables" / "results_table.tex"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    print(f"[ok] wrote {out.relative_to(ROOT)}")


def copy_figures() -> None:
    src = RESULTS / "plots"
    dst = PAPER / "figures"
    dst.mkdir(parents=True, exist_ok=True)
    if not src.exists():
        print(f"[warn] {src} not found; no figures copied.")
        return
    for png in sorted(src.glob("*.png")):
        shutil.copy2(png, dst / png.name)
        print(f"[ok] copied {png.name}")


def main() -> None:
    rows = _load_summary()
    write_results_table(rows)
    copy_figures()


if __name__ == "__main__":
    main()
